[package]
id = "hadal-theme"
name = "Hadal Theme"
version = "0.1.0"
schema_version = 1
authors = ["maikel"]
description = "A deep-sea inspired theme for Zed"
repository = "https://github.com/maikel-479/hadal"

[grammars]
